name: Beta Build

on:
  push:
    branches:
    - beta

jobs:
  firebase-hosting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build:prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:beta
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  firebase-functions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: cd functions && npm install
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}